### ISSUE TITLE
Make trailing line feed optional

### ISSUE THREAD

**Issue by johnfoldager** [vert-x3/vertx-stomp#13]
Make it possible to make trailing line feed optional.

For further information see this RabbitMQ issue: https://github.com/rabbitmq/rabbitmq-stomp/issues/39

**Comment by cescoffier** [comment]
Actually, the trailing line feed is already _optional_. trailing `\n`s are interpreted as `PING` frame (which should be ok).

It does not provide an option to "write" a `\n` in frames (neither in the server nor the client). We could add an option for this.

Can you give more details about the issue / enhancement ?

**Comment by johnfoldager** [comment]
The problem arose when RabbitMQ added the optional linefeed to every STOMP frame. We have some hardware where the firmware was created to not handle that linefeed (the developers wrote a parser for whatever RabbitMQ sent out at the time being). This resulted in parsing-errors in the firmware (RabbitMQ now have a configuration to disable it because of our problems).

Now we need to create STOMP tests for new firmware (that can handle the linefeed) as well as for old firmware. Since the linefeed is optional it would be great to be able to put it at the end of every STOMP frame or not in order to reflect both situations.

**Comment by cescoffier** [comment]
Oh I see. Yes, we can add an option in the server and client options to add a `\n` in the frames. This would be disabled by default, but can be enabled.

The main question is the following: should this "line" be considered as a `PING` frame or not.

**Comment by cescoffier** [comment]
fixed by #17
