### ISSUE TITLE
Handling authentication errors in StompClient version 3.2.1

### ISSUE THREAD

**Issue by cer** [vert-x3/vertx-stomp#18]
My application supplied incorrect credentials to the StompClient and so the server responded to the CONNECT frame with an ERROR frame.

However, because the application hadn't yet been given a chance to set `StompClientConnectionImpl.errorHandler` the authentication failure wasn't passed to the application.

**Comment by cescoffier** [comment]
Nice catch, we would need a higher level error hander.

**Comment by cer** [comment]
As a temporary fix, I changed connect() to add a 'temporary' error handler to the StompClientConnection:

```
        StompClientConnectionImpl scci = new StompClientConnectionImpl(vertx, ar.result(), this, resultHandler);
        scci.errorHandler(frame -> {
                  resultHandler.handle(new FutureFactoryImpl().completedFuture(new RuntimeException("Error")));
                }
```

(I suspect that `new FutureFactoryImpl().completedFuture(new RuntimeException("Error"))` isn't the best way to way to create a failed AsyncResult but oh well )
