### ISSUE TITLE
StompServerTCPConnectionImpl.ping failing with NullPointerException

### ISSUE THREAD

**Issue by astery** [vert-x3/vertx-stomp#22]
I tried to follow [this](http://vertx.io/docs/vertx-stomp/java/#_using_the_stomp_server_with_web_sockets) section of guide and failed. After connection happens and heart beat timeout reached server raises NullPointerException.

To reproduce behaviour look at `WebSocketBridgeTest#testPingFromServer` test [here](https://github.com/astery/vertx-stomp/commit/d147d12033aa70da0fbede107afd3618a1906fa7).

**Comment by cescoffier** [comment]
You are absolutely right, fixing it !
