### ISSUE TITLE
CONNECT frame not handled by writingFrameHandler

### ISSUE THREAD

**Issue by johnfoldager** [vert-x3/vertx-stomp#24]
I've tried the following code:

```
StompClient stompClient = StompClient.create(vertx, stompClientOptions);
	stompClient
		.receivedFrameHandler(frame -> {
			printFrame(frame);
		})
		.writingFrameHandler(frame -> {
			printFrame(frame);
		})
		.connect(ar -> {
			// ....
		});
```

and the first frame that I get printed (from the printFrame method) is the "CONNECTED" frame. I would have guessed that the "CONNECT" frame be the first, but it never gets printed.

**Comment by johnfoldager** [comment]
The same goes for DISCONNECT frame.

**Comment by cescoffier** [comment]
The `CONNECT` frame is fixed.

About `DISCONNECT`, it works when explicitly sending `DISCONNECT` (`disconnect()`).
