### ISSUE TITLE
First Time setPeriodic on PING failes to get canceled

### ISSUE THREAD

**Issue by tbolis** [vert-x3/vertx-stomp#26]
On startup of application and in the first websocket connection the id of the timer set the pinger id is of value zero

code reference:
> io.vertx.ext.stomp.impl.StompServerTCPConnectionImpl#pinger:132

```java
@Override
  public synchronized void configureHeartbeat(long ping, long pong, Handler<StompServerConnection> pingHandler) {
    if (ping > 0) {
      pinger = server.vertx().setPeriodic(ping, l -> pingHandler.handle(this));
    }
    if (pong > 0) {
      ponger = server.vertx().setPeriodic(pong, l -> {
        long delta = System.nanoTime() - lastClientActivity;
        final long deltaInMs = TimeUnit.MILLISECONDS.convert(delta, TimeUnit.NANOSECONDS);
        if (deltaInMs > pong * 2) {
          log.warn("Disconnecting client " + this + " - no client activity in the last " + deltaInMs + " ms");
          close();
        }
      });
    }
  }
```

therefore the `pinger` which is the id of the timer is of value zero

when closing connection and on cancleHeardbeat the check of pinger >0 fails and the timer is not removed

> io/vertx/ext/stomp/impl/StompServerTCPConnectionImpl.java:113

 ```java
public synchronized void cancelHeartbeat() {
    if (pinger > 0) {
      server.vertx().cancelTimer(pinger);
      pinger = 0;
    }

    if (ponger > 0) {
      server.vertx().cancelTimer(ponger);
      ponger = 0;
    }
  }
```

Workaround is to create a once off timer at vertx boot:

`server.vertx().setTimer(1, id -> LOG.info("Cancelling {} Timer as a Workaround for StompServer", id));`

**Comment by cescoffier** [comment]
Yes definitely a bug.

It should be initialize to -1 and not 0, and all test need to check whether or not the value is >= 0.
