### ISSUE TITLE
Stomp Websocket fallbacks

### ISSUE THREAD

**Issue by MazizEsa** [vert-x3/vertx-stomp#34]
Currently if you use stomp over websocket, will it fallback to sockjs if websocket is unavailable?

**Comment by cescoffier** [comment]
No, it won't. To do this, you need to use the stomp event bus bridge (like in https://github.com/vert-x3/vertx-stomp/blob/master/src/test/java/io/vertx/ext/stomp/impl/EventBusBridgeTest.java) and combine it with the SockJS bridge.

**Comment by MazizEsa** [comment]
Any example of the combination that I could look? @cescoffier . Thanks.

**Comment by cescoffier** [comment]
I don't think we have an example, but it should be straightforward:

1. Configure the Stomp event bus bridge to forward Stomp messages to the event bus (for example on the address "stomp")
2. Configure the SockJS event bus bridge to forward messages from the "stomp" address to sockJS.

Do you need a bidirectional link?

**Comment by MazizEsa** [comment]
@cescoffier yup. Need bidirectional. Set it up. With this setup can I use stomp client (over sockjs)?

Im getting this error on the client (web console) 

`{"type":"err","body":"invalid_json"}`

On the sockjs handler (server), it does trigger the SOCKET_CREATED event.

**Comment by vietj** [comment]
@cescoffier shall we close this issue ?

**Comment by cescoffier** [comment]
@MazizEsa if you use SockJS and the bridge, yes you don't need the Stomp bridge. The bridge allows exchanging Stomp frame on websocket.

**Comment by am-kram** [comment]
@cescoffier  : i have the same issue - stomp over sockjs raises this error  ( i tried the stomp handler directly and I don't receive any messages for some reason). I am ok to use the sockjs with bridge as you suggest but the stomp frame is automatically attempted to convert to json and this error is raised:
```
{"type":"err","body":"invalid_json"}
```
```
public void start() throws Exception {
    Router router = Router.router(vertx);
    router.route("/stomp/*").handler(eventBusHandler());
   router.route().handler(StaticHandler.create());

    HttpServer http = vertx.createHttpServer(
    )
      .requestHandler(router::accept)
      .listen(8080);

  }
  private SockJSHandler eventBusHandler() {
    BridgeOptions options = new BridgeOptions()
            .addInboundPermitted(new PermittedOptions().setAddressRegex("stomp.*"));

    return SockJSHandler.create(vertx).bridge(options, event -> {
      if (event.type() == BridgeEventType.SOCKET_CREATED) {
        logger.info("A socket was created");
      }else if(event.type() == BridgeEventType.RECEIVE) {
        logger.info(event.getRawMessage());
      }
      event.complete(true);
    });
  }
```

**Comment by purpleP** [comment]
Can I use `StompClient` to connect to spring sockjs server?

https://github.com/vert-x3/vertx-stomp/issues/34

https://stackoverflow.com/questions/56251809/can-i-use-vertx-stomp-client-to-work-with-sockjs-server

**Comment by am-kram** [comment]
its not compatible - i had to reimpliment it.

**Comment by purpleP** [comment]
> its not compatible - i had to reimpliment it.

@am-kram 
Okay, can you show the code for that?
