### ISSUE TITLE
Frame Ack null value cause Queue/Topic transform method  NPE

### ISSUE THREAD

**Issue by leotu** [vert-x3/vertx-stomp#4]
Account to API:
io.vertx.ext.stomp.Frame.java that "getAck()" method may return null.
````java
   /**
   * Gets the value of the {@code ack} header.
   *
   * @return the {@code ack} header value, {@code null} if not set
   */
  public String getAck() {
    return headers.get(ACK);
  }
````
So io.vertx.ext.stomp.impl.Topic.Subscription constructor -->
protected class Subscription {
...
   protected Subscription(StompServerConnection connection, Frame frame) {
     ...
      this.ackMode = frame.getAck();
    ...
    }
...
}

And, io.vertx.ext.stomp.impl.Queue.Subscription constructor -->
private class Subscription {
    ...
    private Subscription(StompServerConnection connection, Frame frame) {
      ...
      this.ackMode = frame.getAck();
      ...
    }
  }

"this.ackMode" may be null value.

When I used "netty 4.1.x"  sample code "io.netty.example.stomp.StompClient.java" causing below exception!

---------------------
java.lang.NullPointerException
	at io.vertx.ext.stomp.impl.Queue.transform(Queue.java:90)
That code is at "...if (!subscription.ackMode.equals("auto")) {..."

---------------------
java.lang.NullPointerException
	at io.vertx.ext.stomp.impl.Topic.transform(Topic.java:77)
That code is at  "... if (!subscription.ackMode.equals("auto")) { ..."

**Comment by cescoffier** [comment]
Yes, it should be set to 'auto' when `null`. The provided stomp client is a bit too zealous here as it set it to `auto`.
