### ISSUE TITLE
StompClientConnection  reconnect

### ISSUE THREAD

**Issue by f117f** [vert-x3/vertx-stomp#41]
I use vertx-stomp to connect to ActiveMQ successfully, 
and when the ActiveMQ server is closed or the network is disconnected, 
it can not be reconnected automatically, and how to refresh the connection when the server is open or the network is restored. 
stompClientOptions.setReconnectInterval (1000) is invalid.
use java
Thanks very much！

**Comment by deepsleep** [comment]
Hi @f117f , as what I have learned that `StompClientConnection` does not reconnect automatically by default. The method  setReconnectInterval and `setReconnectAttempts` in `StompClientOptions`  only apply to the `NetClientImpl` which handle the underlying Socket connections. By default, the reconnectAttempts value is 0, so you need to set i with a positive value to enable socket reconnection.

In the StompClient level, please refer to the **Handling errors** part in https://vertx.io/docs/vertx-stomp/java/ ; you can handle the disconnect event in `connection.connectionDroppedHandler`.
