### ISSUE TITLE
io.vertx.ext.stomp.Frame constructor issue

### ISSUE THREAD

**Issue by cbdyzj** [vert-x3/vertx-stomp#62]
https://github.com/vert-x3/vertx-stomp/blob/fbd8a7ec6d189d898be9a71e849b7cb718299eae/src/main/java/io/vertx/ext/stomp/Frame.java#L235

hello，I'm having a problem with the constructor of `io.vertx.ext.stomp.Frame`.

I think this line should be `this.headers.putAll(other.headers); `. Since we want to copy headers from `other` frame.

**Comment by vietj** [comment]
right, can you provide a test and fix ?

Julien

**Comment by vietj** [comment]
thanks @cbdyzj much appreciated
