### ISSUE TITLE
Subscribe notification on a closed connection

### ISSUE THREAD

**Issue by racoonman** [vert-x3/vertx-stomp#68]
### Context
I got scared when I saw the code of the class io.vertx.ext.stomp.impl.EventBusBridge lines 70-99 where the subscribe is implemented. According to this code when you have to write a frame to the subscribers it does not capture a possible exception (line 91) that can occur if the connection is closed (java.lang.IllegalStateException: WebSocket is closed). When cycling the subscriptions in order (subscriptions.forEach), it may happen that. 

I got nervous thinking that until I saw that the code that handles the heartbeat (ping-pong), is responsible for closing connections and this will stop happening.

In short, if a connection is disconnected the following subscribed connections to the same address will not receive their Frame until the heartbeat closes this connection.

But, the fact is that the heatbeat is negotiated at the maximum value of both ends, so an endpoint with a very high heartbeat, can cause that connections subscribed to the same address do not receive your message for a long time (2x the heartbeat time).

I think try-catching a possible "java.lang.IllegalStateException" when writing the connection this code can be a good idea and you would not miss those notifications for the last subscribers.

### Version

3.9.0

### Steps to reproduce

The problem can be easly reproduces by subscribing to the same adress multiple times and closing the program.

**Comment by vietj** [comment]
@racoonman can you contribute a fix ?

**Comment by racoonman** [comment]
This is my proposal #69

**Comment by vietj** [comment]
did you encounter this issue in practice ? do you have a stracktrace to share ?

**Comment by racoonman** [comment]
Hi,

When adding an exceptionHandler like this

```
	vertx.exceptionHandler(new Handler<Throwable>() {
            @Override
            public void handle(Throwable e) {
                LOG.error("Exception handler: " + e.getMessage(), e);
            }
        });
```

It prints the problem.

This also prints every conection closed exception when the ping-pong code fails to send PING. So every close connection from the client side will throw an exception.

A simple test could be made by setting a server and subscribing two clients to the same address.

If you synchronize a message from the server while closes the first client before the ping-pong code closes the connection, the second client will not receive the message.

I'll try to make a test of this.

**Comment by racoonman** [comment]
I'm sorry, I can't reproduce the problem through a test.

All my attempts go through closing the Stompclient NetClient and this is handled correctly. 
Can you think of a way to close the netsocket of the netclient so that the close method is not called?

I am only able to reproduce it through a external program with a to the server.

On the other hand, it happens to me that a client has managed to disconnect without triggering the error handling code closing the connection to the client correctly.  And due to the problem of notification of the messages in a sequential way, it causes the rest of the clients to stop receiving the messages.
For the moment, I'll use a version for personal use that will catch the writing and close the connection if it fails, as well as eat the exception so that the rest of the subscribed clients receive their message.

I will continue to investigate to facilitate a test that evidences the problem.

**Comment by racoonman** [comment]
Another propossal for the writing code in the EventBusBridge.java is to use parallelStream


`subscriptions.parallelStream().filter(s -> s.destination.equals(address)).forEach(s -> {`


That way the messages will be notified to every subscriber

**Comment by vietj** [comment]
@racoonman I'm willing to merge this PR for 3.9.3, however parallelStream() is not helpful here can you revert this commit in the pR ?

**Comment by racoonman** [comment]
@vietj Sorry for taking so long to respond. Already changed the PR

**Comment by vietj** [comment]
note this cannot happen in master as the error shall happen asynchronously now.

**Comment by vietj** [comment]
I'll rework a bit the proposed PR because, it needs more changes, i.e the current iteration is done in a foreach and therefore there is no way to stop the iteration when the connection is closed.
