### ISSUE TITLE
Stomp Client connect to non root endpoint

### ISSUE THREAD

**Issue by retbrown** [vert-x3/vertx-stomp#8]
Can the StompClient be extended to take a requestURI in addition to the host and port number. This is to enable usage with a server that is hosting a websocket connection from a request URI rather than the default root of the domain.

ie.

HttpClient client = vertx.createHttpClient().websocket(80, "localhost", "/foo", ...

The above code connects correctly to the server hosting the stomp websocket.

Is there an option to specify foo when using StompClient?

**Comment by cescoffier** [comment]
No this option is not available. However, it would be useful when using STOMP over web sockets, but I'm not sure the current implementation support this (Did you try ?).

**Comment by retbrown** [comment]
Hi @cescoffier thanks for getting back to me. I have given it a try but couldn't get it working so wondered if I had missed something. Will have a further look today and see if I can get it working.

**Comment by cescoffier** [comment]
Hi,

I've implemented the websocket support in https://github.com/vert-x3/vertx-stomp/pull/11.

**Comment by retbrown** [comment]
Thanks Clement. I will get the branch and integrate it with my code and look forward to the 3.3.0 release.

**Comment by cescoffier** [comment]
Just for traceability reason, I will re-open this issue, until the PR is merged (to compute the release notes correctly). I will close it when it will be merged.

**Comment by cescoffier** [comment]
Web socket support added.
