### ISSUE TITLE
Stomp client no support for virtual hosts

### ISSUE THREAD

**Issue by ajunge** [vert-x3/vertx-stomp#9]
In CloudAMQP you have a host, and a virtual host. Host is the name for the IP address to connect to, and the virtual host is the name to put in the "host" field on the CONNECT frame. There is no way to specify that on the actual implementation.
Maybe an "virtualHost" option could help?

**Comment by cescoffier** [comment]
That would be for the client only right ?

**Comment by cescoffier** [comment]
I've added the option and a connection test to Cloud AMQP.

**Comment by ajunge** [comment]
Great! Thanx!. Now just need to wait for 3.3.0 to come out.

**Comment by cescoffier** [comment]
This should be 3.2.1, that is going to be released end of January (so very very soon).

**Comment by ajunge** [comment]
oh. great!

**Comment by johnfoldager** [comment]
I can confirm that it works with 3.2.1 :+1:
